Algoritmo "Soma"
// Disciplina   : [Introdução a Computação]
// Professor: EVANDRO FRANZEN
// Descrição   : Soma de dois números.
// Autor(a)    : Alessandra Elisa Santana
// Data atual  : 06/04/2022
Var
     n1,n2, soma: inteiro
Inicio
     Escreval ("Digite o primeiro valor: ")
     leia (n1)
     Escreval ("Digite o segundo valor: ")
     leia (n2)
     soma <- (n1+n2)
     Escreval ("A soma dos valores é: ",soma)
Fimalgoritmo